- hosts: all

  tasks:
    - name: Display inventory hostname
      command: echo "{{inventory_hostname}}"
    - name: Change the hostname to our standard
      ansible.builtin.hostname:
        name="{{inventory_hostname}}"

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:

    - name: Waiting for server to come back up
      ansible.builtin.wait_for_connection:
