- name: Check status of a service and email if its down
  hosts: all
  tasks:
  - command: service httpd status
      register: result
  - mail:
      to: admin@company.com
      subject: Service Alert
      body: Httpd Service is down {{inventory_hostname}}
    when: result.stdout.find('down') != -1
