-
  hosts: server1
  tasks:
  - block:
    - name: Install MySQL
      yum: name=mysql-server state=present
    - name: Start MySQL Service
      service: name=mysql-server state=started
    become_user: db-user
    when: ansible_facts['distribution'] == 'CentOS'
    rescue:
      - mail:
          to: admin@company.com
          subject: Installation Failed
          body: DB Install Failed at {{ ansible_failed_task.name }}
    always:
      - mail:
          to: admin@company.com
          subject: Installation Status
          body: DB Install Status - {{ ansible_failed_result }}
