- name: Deploy web application
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Install dependencies
      << code hidden >>
    - name: Install MySQL Database
      << code hidden >>
    - name: Start MySQL Service
      << code hidden >>
    - name: Install Python Flask Dependencies
      << code hidden >>
    - name: Run web-server
      << code hidden >>
    - command: cat /var/log/server.log
      register: command_output
      failed_when: 'ERROR' in command_output.stdout
    - mail:
        to: admin@company.com
        subject: Server Configured
        body: Web server has been configured
